FROM rust:1.69

WORKDIR /app

COPY ./Cargo.toml /app/Cargo.toml
COPY ./Cargo.lock /app/Cargo.lock
COPY ./migrations /app/migrations
COPY ./src /app/src
COPY ./.cargo /app/.cargo

RUN cargo build

CMD cargo run --bin main
