FROM rust:1.67

WORKDIR /app

COPY ./Cargo.toml /app/Cargo.toml
COPY ./Cargo.lock /app/Cargo.lock
COPY ./src /app/src
COPY ./migrations /app/migrations
RUN cargo build

CMD ["cargo", "run", "--bin", "main"]
