FROM rust:1.69

WORKDIR /app

COPY ./Cargo.toml /app/Cargo.toml
COPY ./Cargo.lock /app/Cargo.lock
COPY ./migrations /app/migrations
COPY ./.cargo /app/.cargo
COPY ./src /app/src

RUN cargo build

CMD cargo run --bin main
