FROM rust:1.69

WORKDIR /app

COPY ./Cargo.toml /app/Cargo.toml
COPY ./Cargo.lock /app/Cargo.lock
COPY ./migrations /app/migrations
COPY ./tls /app/tls
COPY ./src /app/src

RUN RUSTFLAGS="--cfg uuid_unstable" cargo build

CMD RUSTFLAGS="--cfg uuid_unstable" cargo run --bin main
